[package]
name = "LearningRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# Adding another comment to check socket.dev.

[dependencies]
rand = "0.8.5"
